title: Haiyuan Mei
author: GitHub User
email: haroldmei.cn@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Build Data Analytics solutions, bridge the gap between software engineering and machine learning.
  Explore the cutting edge AI technologies and always on the look for their industrial use cases.


# Build settings
# theme: minima

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge